const GET_USER_REQUEST = "GET_USER_REQUEST";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAULIER = "GET_USER_FAULIER";

const POST_USER_REQUEST = "POST_USER_REQUEST";
const POST_USER_SUCCESS = "POST_USER_SUCCESS";
const POST_USER_FAULIER = "POST_USER_FAULIER";
export {
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAULIER,
  POST_USER_REQUEST,
  POST_USER_SUCCESS,
  POST_USER_FAULIER,
};
